# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/Calculator-ReactNative" # Location of package manifests
    schedule:
      interval: "monthly"
    ignore:
      # Ignore updates to the following libraries since they're updated or tied with expo
      - dependency-name: "@babel/core"
      - dependency-name: "@types/react"
      - dependency-name: "expo"
      - dependency-name: "expo-status-bar"
      - dependency-name: "jest-expo"
      - dependency-name: "react"
      - dependency-name: "react-dom"
      - dependency-name: "react-native"
      - dependency-name: "react-native-web"
      - dependency-name: "react-test-renderer"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pub"
    directory: "/calculator_flutter"
    schedule:
      interval: "monthly"
